### PR TITLE
Improves panic reports to scope and fixes source field on events

### LINKED ISSUE #166: Source field of events is outside of source root
When calculating the `source` field of events, we are taking the path of the first frame, but that could live outside of the repo. We should go through the stacktrace and take the first frame that has a `source` inside the source root.

This makes it impossible for the UI to display source code context for the event.

### PR DESCRIPTION
**Pull request by tonyredondo**
Closes #166 

This `PR` improves support for panic data report in spans with stacktraces (as a log or as an exception) and fixes the source field of the events, to always reference a file inside the source root.

### CODE REVIEW

File: errors/handler.go [hunk 1]
```diff
@@ -27,23 +31,26 @@ type StackFrames struct {
...
 }
 
-func LogErrorInRawSpan(rawSpan *tracer.RawSpan, err **errors.Error) {
+func WriteExceptionEventInRawSpan(rawSpan *tracer.RawSpan, err **errors.Error) {
 	if rawSpan.Tags == nil {
 		rawSpan.Tags = opentracing.Tags{}
 	}
-	if *err == MarkSpanAsError {
+	if *err == markSpanAsError {
 		rawSpan.Tags["error"] = true
```
Comment (drodriguezhdez) [inline errors/handler.go]: `rawSpan.Tags["error"] = true` is present in if clause and else clause.
Can we extract this outside of the if?

File: instrumentation/testing/tb.go [hunk 2]
```diff
@@ -216,14 +218,19 @@ func (test *Test) Helper() {
 	test.t.Helper()
 }
 
+// Log panic data with stacktrace
+func (test *Test) LogPanic(recoverData interface{}, skipFrames int) {
```
Comment (drodriguezhdez) [inline instrumentation/testing/tb.go]: Is this function called automatically by test instrumentation, right?

File: errors/handler.go (hunk 1 above)
Comment (tonyredondo) [reply errors/handler.go]: You're right , I made the changes...

File: instrumentation/testing/tb.go (hunk 2 above)
Comment (tonyredondo) [reply instrumentation/testing/tb.go]: The internal test instrumentation uses `WriteExceptionEvent` because already have the `opentracing.Span` reference. `LogPanic` it's a very similar function but using the `context` to extract the span. Useful for others and manual instrumentation.

Comment (tonyredondo) [reply instrumentation/testing/tb.go]: This `LogPanic` method is exposed in `tb.go` too. So we can use:

```go
func TestBasic(t *testing.T) {
    test := scopeagent.GetTest(t)

    defer func() {
        if r := recover(); r != nil {
            test.LogPanic(r, 1)
        }
    }()

    panic("test")
}
```
