### PR TITLE
Remove multiple panics report

### LINKED ISSUE #113: Multiple panics in the exception view
If a panic is thrown in a span, is reported in that span and gets propagate to the parent. And the same logic repeats until there are no more parents. As a result, the panic gets reported multiple times.

### PR DESCRIPTION
**Pull request by tonyredondo**
Closes #113 

This `PR` removes the double panic report by writing the panic info the first time and then panicking a custom error to only mark the parent spans.

image

image

image

### CODE REVIEW

File: errors/handler.go [hunk 1]
```diff
@@ -27,25 +27,33 @@ type StackFrames struct {
...
+		var exceptionFields = getExceptionLogFields(*err, 1)
+		if rawSpan.Logs == nil {
+			rawSpan.Logs = []opentracing.LogRecord{}
+		}
+		rawSpan.Logs = append(rawSpan.Logs, opentracing.LogRecord{
+			Timestamp: time.Now(),
+			Fields:    exceptionFields,
+		})
+		rawSpan.Tags["error"] = true
+		*err = MarkSpanAsError
```
Comment (fermayo) [inline errors/handler.go]: Is this the exception that gets reported on the CLI when the tests fail?

Comment (tonyredondo) [reply errors/handler.go]: Go is clever enough to append all panic/recover pairs, so in this example the panic standard output is: 
image

Comment (fermayo) [reply errors/handler.go]: None of those frames include the one that originally panicked, right?

Comment (tonyredondo) [reply errors/handler.go]: It's included: 
image

Comment (tonyredondo) [reply errors/handler.go]: But also we have all the `Finish` calls of the parent spans, do you prefer to avoid that frames? maybe I can store the stacktrace when the panic happens.

Comment (fermayo) [reply errors/handler.go]: It's a lot of noise, but I think it's OK for now
